[package]
name = "day-6"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
nom = "7.1.3"
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "count_obstructions_bench"
harness = false
